---

- name: "Install prerequesites"
  package:
    name: openssl
  when: ansible_os_family == "RedHat"

- name: "create user to run artifactory"
  user:
    name: "{{ artifactory_user }}"
    home: "{{ artifactory_home_dir }}"
    shell: /bin/bash
    system: true

- name: 'verify presence of artifactory'
  stat:
    path: "/opt/artifactory/artifactory-{{ artifactory_version }}/webapps/artifactory.war"
  register: artifactory_exists
